# Generated by Django 3.2.13 on 2022-06-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summoner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.IntegerField(null=True)),
                ("rank", models.IntegerField(null=True)),
                ("lp", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=16)),
                ("report_hook", models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Promos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("progress", models.CharField(max_length=5)),
                (
                    "summoner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="summoner.summoner",
                    ),
                ),
            ],
        ),
    ]
