# Generated by Django 3.2.13 on 2022-07-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summoner", "0002_auto_20220627_1903"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summoner",
            name="last_match_id",
        ),
        migrations.RemoveField(
            model_name="summoner",
            name="lp",
        ),
        migrations.RemoveField(
            model_name="summoner",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="summoner",
            name="tier",
        ),
        migrations.DeleteModel(
            name="Promos",
        ),
    ]
