# Generated by Django 3.2.13 on 2022-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner', '0003_auto_20220703_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='account_id',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summoner_id',
            field=models.CharField(max_length=63),
        ),
    ]
