# Generated by Django 3.2.13 on 2022-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoner", "0004_auto_20220715_1530"),
    ]

    operations = [
        migrations.AddField(
            model_name="summoner",
            name="bully_opt_in",
            field=models.BooleanField(default=False),
        ),
    ]
