# Generated by Django 3.2.13 on 2022-06-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("summoner", "0002_auto_20220627_1903"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(max_length=15)),
                ("champion_name", models.CharField(max_length=20)),
                (
                    "summoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="summoner.summoner",
                    ),
                ),
            ],
        ),
    ]
