# Generated by Django 3.2.13 on 2022-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="assists",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="deaths",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="epic_steals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="kda",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="kills",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="penta_kills",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="quadra_kills",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="triple_kills",
            field=models.IntegerField(default=0),
        ),
    ]
