# Generated by Django 3.2.13 on 2022-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0002_auto_20220628_1631"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="lp_diff",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
