# Generated by Django 3.2.13 on 2022-07-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("summoner", "0003_auto_20220703_1517"),
        ("match", "0003_match_lp_diff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("progress", models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name="match",
            name="lp_diff",
        ),
        migrations.CreateModel(
            name="RankedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("lp", models.IntegerField()),
                (
                    "match",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="match.match",
                    ),
                ),
                (
                    "promo",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="match.promos",
                    ),
                ),
                (
                    "summoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="summoner.summoner",
                    ),
                ),
            ],
        ),
    ]
