# Generated by Django 3.2.13 on 2022-07-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0004_auto_20220703_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankedrecord",
            name="promo",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="match.promos",
            ),
        ),
    ]
