# Generated by Django 3.2.13 on 2022-07-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0005_alter_rankedrecord_promo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="kda",
            field=models.FloatField(default=0),
        ),
    ]
