# Generated by Django 3.2.13 on 2022-07-15 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0006_alter_match_kda"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 7, 15, 9, 23, 59, 432368)
            ),
            preserve_default=False,
        ),
    ]
