# Generated by Django 3.2.13 on 2022-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0007_match_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
