# Generated by Django 3.2.13 on 2022-07-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0008_match_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["start_time"]},
        ),
        migrations.AddField(
            model_name="match",
            name="win",
            field=models.BooleanField(default=False),
        ),
    ]
