# Generated by Django 3.2.13 on 2022-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0009_auto_20220715_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="first_blood_assist",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="first_blood_kill",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="first_tower_assist",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="first_tower_kill",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="longest_time_spent_living",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="vision_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="vision_wards_bought",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="wards_placed",
            field=models.IntegerField(default=0),
        ),
    ]
